---


- name: Create config/i3 directory
  file:
    path: ~/.config/i3
    state: directory

- name: Template i3 config
  template:
    src: templates/i3config.j2
    dest: ~/.config/i3/config

- name: Create config/i3status directory
  file:
    path: ~/.config/i3status
    state: directory

- name: Template i3status config
  template:
    src: templates/i3statusconfig.j2
    dest: ~/.config/i3status/config.toml

- fail:

- name: link kitty config
  file:
    src: "~/{{ configs_repo }}/{{ dotconfigdir }}/kitty"
    dest: ~/.config/kitty
    state: link
  when: repo is succeeded

# Background picture
- name: create folder for background picture
  file:
    path: ~/Pictures/Space
    state: directory

- name: copy initial background picture
  copy:
    src: "~/{{ configs_repo }}/background_picture/IMAG7297.JPG"
    dest: "~/Pictures/Space/IMAG7297.JPG"

    # - name: Make sure to start redshift on startup

# gtd todo files
- name: Create todo.sh config dir
  file:
    path: ~/.config/todo
    state: directory

- name: Template todo.sh config
  template:
    src: templates/todoconfig.j2
    dest: ~/.config/todo/config

- name: Create empty todo.sh actions file
  copy:
    content: ""
    dest: ~/.configs/todo/actions
    force: no


- name: Make sure gtd directory is present
  git:
    repo: "git@github.com:{{ git_username }}/{{ todotxtrepo }}.git"
    dest: "~/{{ todotxtrepo }}"
    update: no
  when: ssh is succeeded



# - name: link alacritty config
#   file:
#     src: "~/{{ configs_repo }}/{{ dotconfigdir }}/alacritty"
#     dest: ~/.config/alacritty
#     state: link
#   when: repo is succeeded
