---

- name: Link nixos folder
  file:
    src: "/home/{{ username }}/{{ configs_repo }}/nixos"
    dest: /etc/nixos/configs
    state: link
  become: true
  ignore_errors: true
  # when: repo is succeeded


- name: Template /etc/nixos/configuration.nix
  template:
    src: "/home/{{ username }}/{{ configs_repo }}/templates/nixosconfig.j2"
    dest: /etc/nixos/configuration.nix
  become: true
  ignore_errors: true
  notify: 
    - "nixos-rebuild build"
    - "nixos-rebuild boot"

      # - name: Install local nixos programs
      #   list:
      #     - ansible
      #     - beancount
      #     - broot
      #     - chromium
      #     - evince
      #     - exa
      #     - fava
      #     - fish
      #     - fzf
      #     - glxinfo
      #     - gnumake
      #     - i3status-rust
      #     - kitty
      #     - libGL
      #     - lm-sensors
      #     - mpv-with-scripts
      #     - neovim
      #     - pciutils
      #     - pdfpc
      #     - poetry
      #     - poppler-utils
      #     - python2.7-virtualenv
      #     - python3.9-pip
      #     - python3.9-setuptools
      #     - python3.9-virtualenv
      #     - ripgrep-all
      #     - signal-desktop
      #     - steam
      #     - telegram-desktop
      #     - thefuck
      #     - todo.txt-cli
      #     - upower
      #     - vim
      #     - zoom-us
