---

- name: Create local broot links
  shell: broot -- install
  listen: "install br"

- name: Restart i3 with new config
  shell: i3 restart
  ignore_errors: true
  listen: "restart i3"

- name: Rebuild NixOS based on current configuration
  shell: nixos-rebuild build
  listen: "nixos-rebuild build"

- name: Make current NixOS configuration boot default
  shell: nixos-rebuild boot
  become: true
  ignore_errors: true
  listen: "nixos-rebuild boot"
