theme = "plain"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0


# Add for mouse and keyboard for desktop, for mouse for laptop
[[block]]
block = "custom"
command = "upower --dump | rg percentage | grep -Eo '[0-9]+%$' | tr '\n' ' ' | awk '{print \"M: \"$1\" K: \"$2\" O: \"$3}'"
interval = 1




# [[block]]
# block = "music"
# buttons = ["play", "next"]


# [[block]]
# block = "custom"
# cycle = ["echo ON", "echo OFF"]
# on_click = "/home/ced/Coding/.dotfiles/multiscreens.sh"


[[block]]
# block = "toggle"
block = "custom"
command = "/home/ced/Coding/.dotfiles/multiscreens.sh"
# text = "" # External Screen
# command_state = "~/Coding/.dotfiles/multiscreens.sh check"
# command = "echo TEST"
# command_on = "~/Coding/.dotfiles/multiscreens.sh on"
# command_off = "~/Coding/.dotfiles/multiscreens.sh off"
interval = 1



[[block]]
block = "memory"
display_type = "memory"
clickable = false
format_mem = "{Mupi}% ({Mug}GB)"
# format_mem = "{MFm}MB/{MTm}MB({Mp}%)"
warning_mem = 60.0
critical_mem = 80.0



[[block]]
block = "net"
device = "enp3s0f1"
speed_up = false
speed_down = false


[[block]]
block = "net"
device = "wlp2s0"
speed_up = false
speed_down = false
ssid = true


# For Desktop:
# [[block]]
# block = "nvidia_gpu"
# label = "GT 1030"
# show_memory = false
# show_clocks = true
# interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°C"
chip = "*-isa-*"


[[block]]
block = "cpu"
interval = 5
format = "{barchart} {utilization}%"

[[block]]
block = "load"
interval = 3
format = "{1m} {5m} {15m}"

[[block]]
block = "battery"
driver = "upower"
interval = 7
format = "{percentage}% {time}h ({power}W)"

[[block]]
block = "time"
interval = 1
format = "%Y-%m-%d %R:%S"

[[block]]
block = "sound"
on_click = "pactl set-sink-mute alsa_output.pci-0000_00_1f.3.analog-stereo toggle"
show_volume_when_muted = true


